import React from 'react';
import './Main.css';

const Main = () => {
    return (
        <div className="content">
            <div class="box">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa ipsum, suscipit vitae nisi a, vehicula fermentum risus. Ut ut mi nec velit scelerisque pellentesque vitae at lacus. Nulla commodo neque et mi porta, eu pharetra sapien sollicitudin. Ut consequat augue eu eros rutrum accumsan. Suspendisse at purus vitae nulla tincidunt tincidunt quis vulputate nunc. Cras vestibulum ultrices nibh eu finibus. Nunc accumsan rhoncus ligula, sit amet mollis leo maximus et. Sed malesuada sodales dolor ut suscipit. Vivamus vehicula mollis justo, non tristique ipsum sagittis et. Etiam posuere diam vel enim lacinia, in dignissim ipsum euismod. Duis ut tortor vitae magna dictum volutpat in ac ipsum. Donec pulvinar, metus et semper aliquam, metus erat commodo purus, at aliquam nisl quam sed est. Sed dignissim risus in risus vehicula venenatis. Nunc nec porta ipsum.
                Curabitur sit amet augue rutrum, accumsan enim in, pulvinar est. Vivamus suscipit, augue a pretium accumsan, eros nisi posuere lorem, vitae aliquam eros erat in turpis. Aliquam vel pharetra ligula, a iaculis eros. Integer hendrerit risus non diam venenatis hendrerit sit amet quis ipsum. Maecenas eget dolor in orci volutpat dapibus non nec ipsum. Nullam sodales ultrices odio quis euismod. Nam auctor odio sit amet nulla volutpat, sed condimentum turpis condimentum.
                Ut condimentum lacus erat, sed ullamcorper tellus viverra at. Quisque vestibulum enim eu placerat porttitor. Vivamus nec viverra mauris. Donec tincidunt sed sapien id laoreet. Cras velit mi, tristique at purus nec, ullamcorper ultricies nisi. Donec lacus dolor, mollis vitae augue non, pulvinar ullamcorper massa. Aenean facilisis, nisi ac fermentum sagittis, arcu justo vulputate dolor, eu condimentum eros massa at nunc. Sed magna libero, iaculis id erat eu, dignissim cursus quam. Aenean id orci at dolor finibus tristique.
                Donec eu mauris iaculis, tincidunt tortor a, facilisis lectus. Phasellus id laoreet massa. Aliquam erat volutpat. Suspendisse a elit faucibus nibh vestibulum consectetur. Nam ornare accumsan mattis. Sed ac fringilla metus. Aenean sed tempor metus, vitae vulputate purus. In sit amet feugiat enim. Praesent at commodo ante. Etiam ac blandit arcu. Nunc at tortor odio. Cras aliquet mollis arcu. 
                Etiam consectetur, mauris nec lobortis dictum, nulla lorem malesuada nibh, eget semper ex dolor vel enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ornare erat ac odio auctor faucibus. Nunc pulvinar hendrerit velit quis blandit. Quisque est velit, dapibus dictum feugiat eu, dignissim vitae est. Fusce posuere felis vitae neque condimentum, sed aliquam sapien malesuada. Proin quis dui eget massa bibendum condimentum.</p>
            </div>
            <div class="box">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa ipsum, suscipit vitae nisi a, vehicula fermentum risus. Ut ut mi nec velit scelerisque pellentesque vitae at lacus. Nulla commodo neque et mi porta, eu pharetra sapien sollicitudin. Ut consequat augue eu eros rutrum accumsan. Suspendisse at purus vitae nulla tincidunt tincidunt quis vulputate nunc. Cras vestibulum ultrices nibh eu finibus. Nunc accumsan rhoncus ligula, sit amet mollis leo maximus et. Sed malesuada sodales dolor ut suscipit. Vivamus vehicula mollis justo, non tristique ipsum sagittis et. Etiam posuere diam vel enim lacinia, in dignissim ipsum euismod. Duis ut tortor vitae magna dictum volutpat in ac ipsum. Donec pulvinar, metus et semper aliquam, metus erat commodo purus, at aliquam nisl quam sed est. Sed dignissim risus in risus vehicula venenatis. Nunc nec porta ipsum.
                Curabitur sit amet augue rutrum, accumsan enim in, pulvinar est. Vivamus suscipit, augue a pretium accumsan, eros nisi posuere lorem, vitae aliquam eros erat in turpis. Aliquam vel pharetra ligula, a iaculis eros. Integer hendrerit risus non diam venenatis hendrerit sit amet quis ipsum. Maecenas eget dolor in orci volutpat dapibus non nec ipsum. Nullam sodales ultrices odio quis euismod. Nam auctor odio sit amet nulla volutpat, sed condimentum turpis condimentum.
                Ut condimentum lacus erat, sed ullamcorper tellus viverra at. Quisque vestibulum enim eu placerat porttitor. Vivamus nec viverra mauris. Donec tincidunt sed sapien id laoreet. Cras velit mi, tristique at purus nec, ullamcorper ultricies nisi. Donec lacus dolor, mollis vitae augue non, pulvinar ullamcorper massa. Aenean facilisis, nisi ac fermentum sagittis, arcu justo vulputate dolor, eu condimentum eros massa at nunc. Sed magna libero, iaculis id erat eu, dignissim cursus quam. Aenean id orci at dolor finibus tristique.
                Donec eu mauris iaculis, tincidunt tortor a, facilisis lectus. Phasellus id laoreet massa. Aliquam erat volutpat. Suspendisse a elit faucibus nibh vestibulum consectetur. Nam ornare accumsan mattis. Sed ac fringilla metus. Aenean sed tempor metus, vitae vulputate purus. In sit amet feugiat enim. Praesent at commodo ante. Etiam ac blandit arcu. Nunc at tortor odio. Cras aliquet mollis arcu. 
                Etiam consectetur, mauris nec lobortis dictum, nulla lorem malesuada nibh, eget semper ex dolor vel enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ornare erat ac odio auctor faucibus. Nunc pulvinar hendrerit velit quis blandit. Quisque est velit, dapibus dictum feugiat eu, dignissim vitae est. Fusce posuere felis vitae neque condimentum, sed aliquam sapien malesuada. Proin quis dui eget massa bibendum condimentum.</p>
            </div>
            <div class="box">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa ipsum, suscipit vitae nisi a, vehicula fermentum risus. Ut ut mi nec velit scelerisque pellentesque vitae at lacus. Nulla commodo neque et mi porta, eu pharetra sapien sollicitudin. Ut consequat augue eu eros rutrum accumsan. Suspendisse at purus vitae nulla tincidunt tincidunt quis vulputate nunc. Cras vestibulum ultrices nibh eu finibus. Nunc accumsan rhoncus ligula, sit amet mollis leo maximus et. Sed malesuada sodales dolor ut suscipit. Vivamus vehicula mollis justo, non tristique ipsum sagittis et. Etiam posuere diam vel enim lacinia, in dignissim ipsum euismod. Duis ut tortor vitae magna dictum volutpat in ac ipsum. Donec pulvinar, metus et semper aliquam, metus erat commodo purus, at aliquam nisl quam sed est. Sed dignissim risus in risus vehicula venenatis. Nunc nec porta ipsum.
                Curabitur sit amet augue rutrum, accumsan enim in, pulvinar est. Vivamus suscipit, augue a pretium accumsan, eros nisi posuere lorem, vitae aliquam eros erat in turpis. Aliquam vel pharetra ligula, a iaculis eros. Integer hendrerit risus non diam venenatis hendrerit sit amet quis ipsum. Maecenas eget dolor in orci volutpat dapibus non nec ipsum. Nullam sodales ultrices odio quis euismod. Nam auctor odio sit amet nulla volutpat, sed condimentum turpis condimentum.
                Ut condimentum lacus erat, sed ullamcorper tellus viverra at. Quisque vestibulum enim eu placerat porttitor. Vivamus nec viverra mauris. Donec tincidunt sed sapien id laoreet. Cras velit mi, tristique at purus nec, ullamcorper ultricies nisi. Donec lacus dolor, mollis vitae augue non, pulvinar ullamcorper massa. Aenean facilisis, nisi ac fermentum sagittis, arcu justo vulputate dolor, eu condimentum eros massa at nunc. Sed magna libero, iaculis id erat eu, dignissim cursus quam. Aenean id orci at dolor finibus tristique.
                Donec eu mauris iaculis, tincidunt tortor a, facilisis lectus. Phasellus id laoreet massa. Aliquam erat volutpat. Suspendisse a elit faucibus nibh vestibulum consectetur. Nam ornare accumsan mattis. Sed ac fringilla metus. Aenean sed tempor metus, vitae vulputate purus. In sit amet feugiat enim. Praesent at commodo ante. Etiam ac blandit arcu. Nunc at tortor odio. Cras aliquet mollis arcu. 
                Etiam consectetur, mauris nec lobortis dictum, nulla lorem malesuada nibh, eget semper ex dolor vel enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ornare erat ac odio auctor faucibus. Nunc pulvinar hendrerit velit quis blandit. Quisque est velit, dapibus dictum feugiat eu, dignissim vitae est. Fusce posuere felis vitae neque condimentum, sed aliquam sapien malesuada. Proin quis dui eget massa bibendum condimentum.</p>
            </div>
            <div class="box">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa ipsum, suscipit vitae nisi a, vehicula fermentum risus. Ut ut mi nec velit scelerisque pellentesque vitae at lacus. Nulla commodo neque et mi porta, eu pharetra sapien sollicitudin. Ut consequat augue eu eros rutrum accumsan. Suspendisse at purus vitae nulla tincidunt tincidunt quis vulputate nunc. Cras vestibulum ultrices nibh eu finibus. Nunc accumsan rhoncus ligula, sit amet mollis leo maximus et. Sed malesuada sodales dolor ut suscipit. Vivamus vehicula mollis justo, non tristique ipsum sagittis et. Etiam posuere diam vel enim lacinia, in dignissim ipsum euismod. Duis ut tortor vitae magna dictum volutpat in ac ipsum. Donec pulvinar, metus et semper aliquam, metus erat commodo purus, at aliquam nisl quam sed est. Sed dignissim risus in risus vehicula venenatis. Nunc nec porta ipsum.
                Curabitur sit amet augue rutrum, accumsan enim in, pulvinar est. Vivamus suscipit, augue a pretium accumsan, eros nisi posuere lorem, vitae aliquam eros erat in turpis. Aliquam vel pharetra ligula, a iaculis eros. Integer hendrerit risus non diam venenatis hendrerit sit amet quis ipsum. Maecenas eget dolor in orci volutpat dapibus non nec ipsum. Nullam sodales ultrices odio quis euismod. Nam auctor odio sit amet nulla volutpat, sed condimentum turpis condimentum.
                Ut condimentum lacus erat, sed ullamcorper tellus viverra at. Quisque vestibulum enim eu placerat porttitor. Vivamus nec viverra mauris. Donec tincidunt sed sapien id laoreet. Cras velit mi, tristique at purus nec, ullamcorper ultricies nisi. Donec lacus dolor, mollis vitae augue non, pulvinar ullamcorper massa. Aenean facilisis, nisi ac fermentum sagittis, arcu justo vulputate dolor, eu condimentum eros massa at nunc. Sed magna libero, iaculis id erat eu, dignissim cursus quam. Aenean id orci at dolor finibus tristique.
                Donec eu mauris iaculis, tincidunt tortor a, facilisis lectus. Phasellus id laoreet massa. Aliquam erat volutpat. Suspendisse a elit faucibus nibh vestibulum consectetur. Nam ornare accumsan mattis. Sed ac fringilla metus. Aenean sed tempor metus, vitae vulputate purus. In sit amet feugiat enim. Praesent at commodo ante. Etiam ac blandit arcu. Nunc at tortor odio. Cras aliquet mollis arcu. 
                Etiam consectetur, mauris nec lobortis dictum, nulla lorem malesuada nibh, eget semper ex dolor vel enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ornare erat ac odio auctor faucibus. Nunc pulvinar hendrerit velit quis blandit. Quisque est velit, dapibus dictum feugiat eu, dignissim vitae est. Fusce posuere felis vitae neque condimentum, sed aliquam sapien malesuada. Proin quis dui eget massa bibendum condimentum.</p>
            </div>
            <div class="box">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa ipsum, suscipit vitae nisi a, vehicula fermentum risus. Ut ut mi nec velit scelerisque pellentesque vitae at lacus. Nulla commodo neque et mi porta, eu pharetra sapien sollicitudin. Ut consequat augue eu eros rutrum accumsan. Suspendisse at purus vitae nulla tincidunt tincidunt quis vulputate nunc. Cras vestibulum ultrices nibh eu finibus. Nunc accumsan rhoncus ligula, sit amet mollis leo maximus et. Sed malesuada sodales dolor ut suscipit. Vivamus vehicula mollis justo, non tristique ipsum sagittis et. Etiam posuere diam vel enim lacinia, in dignissim ipsum euismod. Duis ut tortor vitae magna dictum volutpat in ac ipsum. Donec pulvinar, metus et semper aliquam, metus erat commodo purus, at aliquam nisl quam sed est. Sed dignissim risus in risus vehicula venenatis. Nunc nec porta ipsum.
                Curabitur sit amet augue rutrum, accumsan enim in, pulvinar est. Vivamus suscipit, augue a pretium accumsan, eros nisi posuere lorem, vitae aliquam eros erat in turpis. Aliquam vel pharetra ligula, a iaculis eros. Integer hendrerit risus non diam venenatis hendrerit sit amet quis ipsum. Maecenas eget dolor in orci volutpat dapibus non nec ipsum. Nullam sodales ultrices odio quis euismod. Nam auctor odio sit amet nulla volutpat, sed condimentum turpis condimentum.
                Ut condimentum lacus erat, sed ullamcorper tellus viverra at. Quisque vestibulum enim eu placerat porttitor. Vivamus nec viverra mauris. Donec tincidunt sed sapien id laoreet. Cras velit mi, tristique at purus nec, ullamcorper ultricies nisi. Donec lacus dolor, mollis vitae augue non, pulvinar ullamcorper massa. Aenean facilisis, nisi ac fermentum sagittis, arcu justo vulputate dolor, eu condimentum eros massa at nunc. Sed magna libero, iaculis id erat eu, dignissim cursus quam. Aenean id orci at dolor finibus tristique.
                Donec eu mauris iaculis, tincidunt tortor a, facilisis lectus. Phasellus id laoreet massa. Aliquam erat volutpat. Suspendisse a elit faucibus nibh vestibulum consectetur. Nam ornare accumsan mattis. Sed ac fringilla metus. Aenean sed tempor metus, vitae vulputate purus. In sit amet feugiat enim. Praesent at commodo ante. Etiam ac blandit arcu. Nunc at tortor odio. Cras aliquet mollis arcu. 
                Etiam consectetur, mauris nec lobortis dictum, nulla lorem malesuada nibh, eget semper ex dolor vel enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ornare erat ac odio auctor faucibus. Nunc pulvinar hendrerit velit quis blandit. Quisque est velit, dapibus dictum feugiat eu, dignissim vitae est. Fusce posuere felis vitae neque condimentum, sed aliquam sapien malesuada. Proin quis dui eget massa bibendum condimentum.</p>
            </div>
            <div class="box">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa ipsum, suscipit vitae nisi a, vehicula fermentum risus. Ut ut mi nec velit scelerisque pellentesque vitae at lacus. Nulla commodo neque et mi porta, eu pharetra sapien sollicitudin. Ut consequat augue eu eros rutrum accumsan. Suspendisse at purus vitae nulla tincidunt tincidunt quis vulputate nunc. Cras vestibulum ultrices nibh eu finibus. Nunc accumsan rhoncus ligula, sit amet mollis leo maximus et. Sed malesuada sodales dolor ut suscipit. Vivamus vehicula mollis justo, non tristique ipsum sagittis et. Etiam posuere diam vel enim lacinia, in dignissim ipsum euismod. Duis ut tortor vitae magna dictum volutpat in ac ipsum. Donec pulvinar, metus et semper aliquam, metus erat commodo purus, at aliquam nisl quam sed est. Sed dignissim risus in risus vehicula venenatis. Nunc nec porta ipsum.
                Curabitur sit amet augue rutrum, accumsan enim in, pulvinar est. Vivamus suscipit, augue a pretium accumsan, eros nisi posuere lorem, vitae aliquam eros erat in turpis. Aliquam vel pharetra ligula, a iaculis eros. Integer hendrerit risus non diam venenatis hendrerit sit amet quis ipsum. Maecenas eget dolor in orci volutpat dapibus non nec ipsum. Nullam sodales ultrices odio quis euismod. Nam auctor odio sit amet nulla volutpat, sed condimentum turpis condimentum.
                Ut condimentum lacus erat, sed ullamcorper tellus viverra at. Quisque vestibulum enim eu placerat porttitor. Vivamus nec viverra mauris. Donec tincidunt sed sapien id laoreet. Cras velit mi, tristique at purus nec, ullamcorper ultricies nisi. Donec lacus dolor, mollis vitae augue non, pulvinar ullamcorper massa. Aenean facilisis, nisi ac fermentum sagittis, arcu justo vulputate dolor, eu condimentum eros massa at nunc. Sed magna libero, iaculis id erat eu, dignissim cursus quam. Aenean id orci at dolor finibus tristique.
                Donec eu mauris iaculis, tincidunt tortor a, facilisis lectus. Phasellus id laoreet massa. Aliquam erat volutpat. Suspendisse a elit faucibus nibh vestibulum consectetur. Nam ornare accumsan mattis. Sed ac fringilla metus. Aenean sed tempor metus, vitae vulputate purus. In sit amet feugiat enim. Praesent at commodo ante. Etiam ac blandit arcu. Nunc at tortor odio. Cras aliquet mollis arcu. 
                Etiam consectetur, mauris nec lobortis dictum, nulla lorem malesuada nibh, eget semper ex dolor vel enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ornare erat ac odio auctor faucibus. Nunc pulvinar hendrerit velit quis blandit. Quisque est velit, dapibus dictum feugiat eu, dignissim vitae est. Fusce posuere felis vitae neque condimentum, sed aliquam sapien malesuada. Proin quis dui eget massa bibendum condimentum.</p>
            </div>
        </div>
    );
};

export default Main;
